all:count scheduler l try maysubmit

count:count.c
	gcc -o count count.c
		
scheduler:scheduler.c
	gcc -o scheduler scheduler.c

l:l.c
	gcc -o l l.c

try:try.c
	gcc -o try try.c

maysubmit:maysubmit.c
	gcc -o maysubmit maysubmit.c

clean:
	rm -f count 
	rm -f scheduler
	rm -f try
	rm -f l
	rm -f maysubmit