all:count scheduler scheduler1

count:count.c
	gcc -o count count.c
		
scheduler:scheduler.c
	gcc -o scheduler scheduler.c

scheduler1:scheduler1.c
	gcc -o scheduler1 scheduler1.c

clean:
	rm -f count 
	rm -f scheduler